### PR TITLE
Plant CI

### PR DESCRIPTION
**Pull request by lucafavatella**
@mrallen1 It looks to me your fork of basho_bench is the most up-to-date, hence I am proposing PR.

I saw you removed CI, I wonder whether you would be willing to re-add it. This PR proposes basic configuration. (You would also need to enable this repo in your Travis account too.)

While trying to run your fork of basho_bench, I got a seed_s error (OTP 19) hence I decided to plant some CI and it looks like dialyzer&xref have some complaints about rand that might be meaningful (among others).

### CODE REVIEW

**Comment by lucafavatella** [comment]
I added to CI minimum load test that shall be more a meaningful test.

It [gets stuck](https://travis-ci.org/lucafavatella/basho_bench/jobs/254926406#L994) with:
```
16:19:05.995 [error] Error in process <0.136.0> with exit value:

{function_clause,[{rand,seed_s,[{43,24,13}],[{file,"rand.erl"},{line,87}]},{rand,seed,1,[{file,"rand.erl"},{line,82}]},{basho_bench_worker,worker_init,1,[{file,"/home/travis/build/lucafavatella/basho_bench/_build/default/lib/basho_bench/src/basho_bench_worker.erl"},{line,220}]}]}
```

**Comment by lucafavatella** [comment]
> I added to CI minimum load test that shall be more a meaningful test.
> 
> It gets stuck with:
> 
> 16:19:05.995 [error] Error in process <0.136.0> with exit value:
> 
> {function_clause,[{rand,seed_s,[{43,24,13}],[{file,"rand.erl"},{line,87}]},{rand,seed,1,[{file,"rand.erl"},{line,82}]},{basho_bench_worker,worker_init,1,[{file,"/home/travis/build/lucafavatella/basho_bench/_build/default/lib/basho_bench/src/basho_bench_worker.erl"},{line,220}]}]}

I think I got it. Commit https://github.com/mrallen1/basho_bench/commit/49fd1fd#diff-383e4e6a0839e0756cacc9f41f2c489dR220 fixed compilation - not semantics.

**Comment by jadeallenx** [comment]
No doubt it needs a bit of work, but I haven't spent any time on it since the last part of May, and it's probably time to do that.

Appreciate the PR - I am not opposed to re-enabling travis but I didn't want the old config lying around when I wasn't using it.  Hope to have some time to look at this later this week.

**Comment by lucafavatella** [comment]
At 8cb2212 dialyzer passes. xref failing still, the smoke load test fails too (eleveldb not in path).

**Comment by lucafavatella** [comment]
I force-pushed a few commits.

The issue now is that id passed to new/1 of driver is like `{single_worker,1,1}`. It appears that recent commits broke the callback API (new and run) compatibility - see https://github.com/mrallen1/basho_bench/commit/8d761d7

@mrallen1 Do you agree that it would be desiderable to have in this same repo - even if not in side src/ - a selection of drivers? (I have in mind ets, dets, a dummy one (null?), a file-based one, an http one.) Those would be more likely be updated in sync with code.

**Comment by lucafavatella** [comment]
I am not fixing xref: recent code changes introduces some more dynamic calls (e.g. `M:f()`).

**Comment by lucafavatella** [comment]
Only error I get now is during graph generation:
```
Rscript --vanilla priv/summary.r -i tests/current

[1] "plyr"

Loading required package: plyr

Installing package(s) into ‘/usr/local/lib/R/site-library’

(as ‘lib’ is unspecified)

Warning in install.packages(p, repos = "http://lib.stat.cmu.edu/R/CRAN") :

  'lib = "/usr/local/lib/R/site-library"' is not writable

Error in install.packages(p, repos = "http://lib.stat.cmu.edu/R/CRAN") : 

  unable to install packages

Calls: source -> eval.with.vis -> eval.with.vis -> install.packages

Execution halted

make: *** [results] Error 1
```

I understand fix is setting R_LIBS - may try tomorrow.

**Comment by lucafavatella** [comment]
> I understand fix is setting R_LIBS - may try tomorrow.

After setting R_libs I get error:
```
Rscript --vanilla priv/summary.r -i tests/current

[1] "plyr"

Loading required package: plyr

Installing package(s) into ‘/home/travis/build/lucafavatella/basho_bench/tmp/R_libs’

(as ‘lib’ is unspecified)

Error in library(p, character.only = TRUE) : 

  there is no package called ‘plyr’

Calls: source -> eval.with.vis -> eval.with.vis -> library

In addition: Warning message:

In getDependencies(pkgs, dependencies, available, lib) :

  package ‘plyr’ is not available (for R version 2.14.1)

Execution halted

make: *** [results] Error 1
```

**Comment by lucafavatella** [comment]
As of 02c9c7d, CI passes (xref allowed failure).

**Comment by lucafavatella** [comment]
Graph obtained on Travis CI at 488eeb2
summary
:

**Comment by jadeallenx** [comment]
Looks good, thanks!

**Comment by jadeallenx** [comment]
travis is enabled now. I guess I should've done things in reverse order :)

**Pull request merged**
